http4s/rho

- swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala
- swagger/src/main/scala/org/http4s/rho/swagger/models.scala
Also clean up some of the types emitted.
I'll merge this soon if there are no objections.
> Generate empty maps in the swagger.json

- .gitignore
- examples/src/main/scala/com/http4s/rho/swagger/demo/MyService.scala
- swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala
- swagger/src/main/scala/org/http4s/rho/swagger/package.scala
- swagger/src/test/scala/org/http4s/rho/swagger/SwaggerModelsBuilderSpec.scala
closes #69 
@cencarnacion, I noticed you've pushed a fix for the same issue.
> Check for errors on model building and support Process and Task results

- core/src/main/scala/org/http4s/rho/RhoAction.scala
- core/src/main/scala/org/http4s/rho/bits/PathTree.scala
- core/src/test/scala/org/http4s/rho/CodecRouterSpec.scala
- core/src/test/scala/org/http4s/rho/ResultSpec.scala
- core/src/test/scala/org/http4s/rho/RhoServiceSpec.scala
- core/src/test/scala/org/http4s/rho/bits/ResponseGeneratorSpec.scala
- core/src/test/scala/org/http4s/rhotest/ApiExamples.scala
- examples/src/main/scala/com/http4s/rho/hal/plus/swagger/demo/package.scala
- examples/src/main/scala/com/http4s/rho/swagger/demo/JsonEncoder.scala
- examples/src/main/scala/com/http4s/rho/swagger/demo/Main.scala
- project/build.scala
- swagger/src/test/scala/org/http4s/rho/swagger/SwaggerModelsBuilderSpec.scala
Some cleanup associated with the version bump.
> Bump http4s to 0.7.0

- core/src/main/scala/org/http4s/rho/bits/PathTree.scala
- core/src/test/scala/org/http4s/rho/bits/PathTreeSpec.scala
@kryptt, a quick review would be appreciated. I believe this is what we discussed on gitter.
> PathTree doesnt return a MethodNotAllowed on OPTIONS requests

- .travis.yml
- core/src/main/scala/org/http4s/rho/RhoService.scala
- core/src/main/scala/org/http4s/rho/RouteExecutable.scala
- core/src/test/scala/org/http4s/rho/ApiTest.scala
- core/src/test/scala/org/http4s/rho/CodecRouterSpec.scala
- core/src/test/scala/org/http4s/rho/ParamDefaultValueSpec.scala
- core/src/test/scala/org/http4s/rho/RequestRunner.scala
- core/src/test/scala/org/http4s/rho/RhoServiceSpec.scala
- core/src/test/scala/org/http4s/rho/bits/HListToFuncSpec.scala
- core/src/test/scala/org/http4s/rho/bits/PathTreeSpec.scala
- examples/src/main/scala/com/http4s/rho/hal/plus/swagger/demo/ServerApp.scala
- examples/src/main/scala/com/http4s/rho/swagger/demo/Main.scala
- project/build.scala
The change triggers a lot of changes in the tests and a couple in RhoService.
> Upgrade to http4s-0.9.0

- .travis.yml
- bin/travis
- build.sbt
- project/VersionedGhPages.scala
- project/build.scala
Follows the same basic strategy as the main http4s repo.
> Cross build for Scalaz 7.2

- swagger/src/main/scala/org/http4s/rho/swagger/package.scala
- swagger/src/test/scala/org/http4s/rho/swagger/SwaggerModelsBuilderSpec.scala
Otherwise we don't generate a valid Swagger file.
> Return the type string for the NoContent response in swagger

- core/src/main/scala/org/http4s/rho/Router.scala
@bryce-anderson this is necessary for me to implement the following function
```scala
// create a PATCH route from the POST route, just changing the
// Method and Response body
def createPatchRoute[T <: HList](route: RhoRoute[T]): RhoRoute[T] =
???
```
In the implementation of this method I need to access the `CodecRouter` type tag and copy it to a modified `CodecRouter`. If I don't do this I get `Any` as the type of the body.
Note that the whole thing is a work-around because I was not able to abstract some code between similar POST and PATCH routes without losing the precise response types.
> Expose the type tag of a CodecRouter

- .travis.yml
- core/src/main/scala/org/http4s/rho/RhoService.scala
- project/build.scala
Also updated Http4s dependency
> Fixed issue #136 and added Scala-2.12 cross compile

- core/src/main/scala/org/http4s/rho/bits/ResultResponse.scala
- swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala
- swagger/src/main/scala/org/http4s/rho/swagger/TypeBuilder.scala
- swagger/src/main/scala/org/http4s/rho/swagger/models.scala
- swagger/src/test/scala/org/http4s/rho/swagger/SwaggerModelsBuilderSpec.scala
The swagger output for Map's both straight up and within another case class was an array instead of a object. 
This PR should correct the issue.
> Fixed Swagger Output of Map types

- swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala
- swagger/src/main/scala/org/http4s/rho/swagger/TypeBuilder.scala
- swagger/src/main/scala/org/http4s/rho/swagger/models.scala
- swagger/src/test/scala/org/http4s/rho/swagger/TypeBuilderSpec.scala
Also properly smoke tested. Any way to generate the full json and run it against a linter?
> Now properly supports sealed traits & sealed enums

- swagger/src/main/scala/org/http4s/rho/swagger/TypeBuilder.scala
- swagger/src/test/scala/org/http4s/rho/swagger/SwaggerModelsBuilderSpec.scala
Apparently that's the proper way to go.
> Added type: "object" to generated object types

- core/src/main/scala/org/http4s/rho/AuthedContext.scala
- core/src/main/scala/org/http4s/rho/bits/ResponseGenerator.scala
- core/src/test/scala/org/http4s/rho/ApiTest.scala
- core/src/test/scala/org/http4s/rho/ResultSpec.scala
- core/src/test/scala/org/http4s/rho/RhoServiceSpec.scala
- core/src/test/scala/org/http4s/rho/bits/ResponseGeneratorSpec.scala
- examples/src/main/scala/com/http4s/rho/hal/plus/swagger/demo/StaticContentService.scala
- examples/src/main/scala/com/http4s/rho/swagger/demo/MyService.scala
- examples/src/main/scala/com/http4s/rho/swagger/demo/StaticContentService.scala
- project/build.scala
Are we ok with unsafeFromLong or should that be handled?
> upgrade to http4s 0.17-RC1

- .travis.yml
- project/build.scala
Update to 0.17.0 for publishing newest version.
> Update Version to 0.17.0

- build.sbt
- project/VersionedGhPages.scala
- project/build.properties
- project/plugins.sbt
I was able to build with sbt 1.0, 
Works :
- publishing to GH Pages
- Build the library
- Unit tests
Not tested :
- Publishing the project
> Build with sbt 1.0 (#196)

- examples/src/main/scala/com/http4s/rho/hal/plus/swagger/demo/package.scala
- examples/src/main/scala/com/http4s/rho/swagger/demo/MyService.scala
> Move example service imports to the top

- core/src/main/scala/org/http4s/rho/bits/StringParser.scala
- core/src/test/scala/ApiExamples.scala
- core/src/test/scala/org/http4s/rho/bits/StringParserSpec.scala
> parsers for Date and UUID types

- README.md
- Rho.md
Apologies for putting it in root. Let me know where it should go.
> add a tutorial doc

- Rho.md
Snippets from current `Rho.md` do not compile and also do not describe all used constructs. I'm not sure my version is entirely correct and follow existing practices, but would save me quite some time when I first tried Rho.
> Documentation improvements

- bin/travis
- core/src/main/scala/org/http4s/rho/AuthedContext.scala
Fixed building the docs, and added a step to travis to also check the docs.
> Correct Doc building

- swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala
- swagger/src/test/scala/org/http4s/rho/swagger/SwaggerModelsBuilderSpec.scala
> Mark non-Option body parameters as required.

- .travis.yml
- build.sbt
- core/src/test/scala/ApiExamples.scala
- core/src/test/scala/org/http4s/rho/ApiTest.scala
- core/src/test/scala/org/http4s/rho/CodecRouterSpec.scala
- core/src/test/scala/org/http4s/rho/RhoRoutesSpec.scala
- core/src/test/scala/org/http4s/rho/bits/PathTreeSpec.scala
- hal/src/main/scala/org/http4s/rho/hal/LinkObjectSerializer.scala
- swagger/src/test/scala/org/http4s/rho/swagger/SwaggerModelsBuilderSpec.scala
Cleanup some unused function parameter's that where found by Scala 2.12.8 that where not found by Scala 2.12.6.
> Scala 2.12.8 Update

- bin/travis
- build.sbt
- project/RhoPlugin.scala
- project/plugins.sbt
Adding [MIMA](https://github.com/lightbend/mima) configuration and making it run after unit tests in travis build
> Adding MIMA Binary Compatibility Checking

- core/src/main/scala/org/http4s/rho/bits/StringParser.scala
- core/src/test/scala/org/http4s/rho/bits/StringParserSpec.scala
- examples/src/main/scala/com/http4s/rho/swagger/demo/MyRoutes.scala
I would like to propose adding `map` and `rmap` functions to `StringParser`, in order to simplify defining new parsers on top of existing definitions. The idea is inspired by a similar solution in circe ([`io.circe.Decoder.map`](https://github.com/circe/circe/blob/master/modules/core/shared/src/main/scala/io/circe/Decoder.scala#L94) and [`io.circe.Decoder.emap`](https://github.com/circe/circe/blob/master/modules/core/shared/src/main/scala/io/circe/Decoder.scala#L335) )
> Add StringParser.map and StringParser.rmap

- swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala
- swagger/src/test/scala/org/http4s/rho/swagger/SwaggerModelsBuilderSpec.scala
> Generate precise consumed media types

- swagger/src/main/scala/org/http4s/rho/swagger/TypeBuilder.scala
- swagger/src/test/scala/org/http4s/rho/swagger/TypeBuilderSpec.scala
… refering to nonexistent model.
> Fix a regression causing enum properties to be modeled as RefProperty

- swagger-ui/src/main/scala/com/http4s/rho/swagger/ui/SwaggerUi.scala
- swagger/src/main/scala/org/http4s/rho/swagger/SwaggerSupport.scala
- swagger/src/test/scala/org/http4s/rho/swagger/SwaggerSupportSpec.scala
> Add swagger.yaml in parallel to swagger.json (#415)

- .github/workflows/ci.yml
- .github/workflows/mima.yml
- .github/workflows/release.yml
- core/src/main/scala/org/http4s/rho/bits/QueryParser.scala
- core/src/main/scala/org/http4s/rho/package.scala
- core/src/test/scala/org/http4s/rho/CodecRouterSpec.scala
- core/src/test/scala/org/http4s/rho/RequestRunner.scala
- hal/src/test/scala/org/http4s/rho/hal/HalDocBuilderSpec.scala
- project/Dependencies.scala
and fix deprecations and exhaustivity checks
> Update Scala versions

- project/Dependencies.scala
Reverts http4s/rho#531 overzealous merging of scala steward updates....
> Revert "Update scala-xml to 2.0.0"

- swagger/src/main/scala/org/http4s/rho/swagger/TypeBuilder.scala
- swagger/src/test/scala/org/http4s/rho/swagger/TypeBuilderSuite.scala
This fixes https://github.com/http4s/rho/issues/573. All tests + 2 new ones are passing.
> #573 Handle nonclass Scala types and add tests
