http4s/rho

core/src/main/scala/org/http4s/rho/bits/ParserResult.scala, core/src/main/scala/org/http4s/rho/bits/PathTree.scala, core/src/main/scala/org/http4s/rho/bits/RhoPathTree.scala, core/src/test/scala/org/http4s/rho/RhoServiceSpec.scala
__Note:__ This PR may not be quite finished: it could use some polish with regard to the ```PathTree``` abstraction; in particular requiring a ```Method``` makes it less abstract.
This PR moves resolution of the HTTP method to the end of the path matching process. This has two major effects:
* It will lower performance as more paths must now be considered.
* It allows for easy return of 405 responses due to the knowledge of what methods are available to a path.
I think the 405 response is more valuable than the small performance advantage. This is a feature that is missing from the http4s core-dsl as noted in issue https://github.com/http4s/http4s/issues/234.
=> Move HTTP method resolution to the end of the route match

swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala
If the whole ship is sinking, we should probably just let it go. I
expect this to not happen considering the logic wrapped in the try.
cc/@LeifW
=> Change error catch in the ModelBuilder to only catch NonFatal exceptions

core/src/main/scala/org/http4s/rho/bits/PathTree.scala, core/src/test/scala/org/http4s/rho/RhoServiceSpec.scala, core/src/test/scala/org/http4s/rho/bits/RhoPathTreeSpec.scala
Before this, paths such as `/foo/bar` would cause request to `/foo` to return a 405 Method Not Allowed, which I believe is wrong.
I'll merge this soon barring objections.
=> Fix problem with yield 405 when no paths are defined

swagger/src/main/scala/org/http4s/rho/swagger/SwaggerSupport.scala
Because the model is done during class initialization we can count on
the swagger model being constant once its passed to the user. Therefor,
we should cache the result so we don't waste resources transforming
things back and forth into text.
=> Cache the swagger json.

core/src/main/scala/org/http4s/rho/ExecutableCompiler.scala, core/src/main/scala/org/http4s/rho/bits/HeaderAST.scala, core/src/main/scala/org/http4s/rho/package.scala, core/src/test/scala/org/http4s/rho/ApiTest.scala, core/src/test/scala/org/http4s/rho/RhoServiceSpec.scala, core/src/test/scala/org/http4s/rhotest/ApiExamples.scala, examples/src/main/scala/com/http4s/rho/swagger/demo/MyService.scala, swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerModelsBuilderSpec.scala
It turns out that there was a redundency in the HeaderAST: HeaderCapture and HeaderMapper are basically the same thing where HeaderMapper(key, identity) == HeaderCapture.
HeaderCapture now can take a default should the header not exist, and can return an alternate response should the header not be suitable in some way.
Some functions were also renamed to better reflect what they do.
=> Remove ADT member from HeaderAST

core/src/main/scala/org/http4s/rho/bits/ResultMatcher.scala, core/src/test/scala/org/http4s/rhotest/ApiExamples.scala
closes #79
We don't get any metadata, but some http4s idioms like websockets will return a Response.
=> Add support for the http4s.Response as a Result

core/src/main/scala/org/http4s/rho/bits/ResultInfo.scala, swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala
It turns out that the only existing use cases of `ResultInfo` are in collections where `Empty` is discarded anyhow.
It seems more fun to remove code these days. :smile:
=> Remove `Empty` from the ResultInfo ADT.

core/src/main/scala/org/http4s/rho/Router.scala, core/src/main/scala/org/http4s/rho/bits/HeaderAST.scala, core/src/main/scala/org/http4s/rho/bits/QueryAST.scala, core/src/test/scala/org/http4s/rho/ApiTest.scala, core/src/test/scala/org/http4s/rho/RhoServiceSpec.scala, core/src/test/scala/org/http4s/rhotest/ApiExamples.scala
closes #86
The order of the type arguments to a Shapeless Prepend were reversed leading to incorrect type.
=> Fix Prepend type param ordering

examples/src/main/resources/swagger-ui/index.html, examples/src/main/scala/com/http4s/rho/swagger/demo/MyService.scala, swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala, swagger/src/main/scala/org/http4s/rho/swagger/TypeBuilder.scala, swagger/src/main/scala/org/http4s/rho/swagger/models.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerModelsBuilderSpec.scala
1. Introduce `ComplexDataType` as a new sub class for `DataType` to
distinguish from the primitive data types supported by `swagger` out of
the box.
2. Modify interface of `QueryParameter` and `AbstractProperty` in model to
introduce the `$ref` field for referencing the complex data type. Note
that `RefParameter` and `RefProperty` coming from the Java library do
not work in this case, since they seem to be redeemed for other
purposes. Unfortunately both swagger wiki and java library are very
vague (if not specified at all) how complex type other than the
primitives should be referenced in the query parameter, what I come up
with sort of falls into the realm of “rule-of-thumb” .
(forgot to mention, I also change how the `array` type should be represented, and I believe this is the right …
=> to address #89

examples/src/main/scala/com/http4s/rho/Helpers.scala, examples/src/main/scala/com/http4s/rho/hal/plus/swagger/demo/ServerApp.scala, examples/src/main/scala/com/http4s/rho/swagger/demo/Main.scala, examples/src/main/scala/com/http4s/rho/swagger/demo/StaticContentService.scala
See Issue #97.
This includes a bit of a 'shim' that should be a part of http4s. The orElse functionality is reintroduced with a syntax class that checks for 404 NotFound responses.
=> Make the examples work again

core/src/main/scala/org/http4s/rho/PathBuilder.scala, core/src/test/scala/org/http4s/rho/RhoServiceSpec.scala
Currently the behavior would be to accept the string in construction but it would never be matched because uri segments will be broken up by the '/' chars. This PR does the breaking up for the user.
=> Construct paths without manually breaking up the uri sections

core/src/main/scala/org/http4s/rho/PathBuilder.scala, core/src/main/scala/org/http4s/rho/QueryBuilder.scala, core/src/main/scala/org/http4s/rho/RequestLineBuilder.scala, core/src/main/scala/org/http4s/rho/RhoRoute.scala, core/src/main/scala/org/http4s/rho/RhoService.scala, core/src/main/scala/org/http4s/rho/RouteExecutable.scala, core/src/main/scala/org/http4s/rho/RoutePrependable.scala, core/src/main/scala/org/http4s/rho/Router.scala, core/src/test/scala/org/http4s/rho/ApiTest.scala, core/src/test/scala/org/http4s/rho/RequestRunner.scala, core/src/test/scala/org/http4s/rho/RhoServiceSpec.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerSupportSpec.scala
The idea is that most route construction types can now do the following:
val service = GET / "bar"
val prefixedService = "foo" /: service
We could add capturing prefixes if we wanted to drop support for this from routers but
that would rule out prefixing an already constructed service which is probably the
dominant use case.
=> Route construction can add a non-capturing prefix

core/src/main/scala/org/http4s/rho/CompileService.scala, core/src/main/scala/org/http4s/rho/RhoService.scala, core/src/main/scala/org/http4s/rho/RouteExecutable.scala, core/src/main/scala/org/http4s/rho/bits/ResultResponse.scala, core/src/test/scala/org/http4s/rho/ParamDefaultValueSpec.scala, core/src/test/scala/org/http4s/rho/RequestRunner.scala, core/src/test/scala/org/http4s/rho/ResultSpec.scala, core/src/test/scala/org/http4s/rho/bits/PathTreeSpec.scala, examples/src/main/scala/com/http4s/rho/hal/plus/swagger/demo/Routes.scala, examples/src/main/scala/com/http4s/rho/hal/plus/swagger/demo/ServerApp.scala, examples/src/main/scala/com/http4s/rho/hal/plus/swagger/demo/StaticContentService.scala, examples/src/main/scala/com/http4s/rho/swagger/demo/Main.scala, examples/src/main/scala/com/http4s/rho/swagger/demo/MyService.scala, examples/src/main/scala/com/http4s/rho/swagger/demo/StaticContentService.scala, project/build.scala, swagger/src/main/scala/org/http4s/rho/swagger/TypeBuilder.scala
Summary of changes:
* Service and HttpService moved from org.http4s.server to org.http4s so lots of changed imports.
* http4s dropped its home grown DateTime in favor of the java.time.Instant. The swagger TypeBuilder had to be changed accordingly. Also some tests needed changing.
=> Upgrade to http4s 0.12.0

README.md, core/src/main/scala/org/http4s/rho/Result.scala, core/src/main/scala/org/http4s/rho/bits/PathTree.scala, core/src/test/scala/ApiExamples.scala, core/src/test/scala/org/http4s/rho/ApiTest.scala, project/build.scala
The examples here won't build with 2.11.8. Its fixed by a patch in http4s proper but its not clear if that is a real fix or just a band-aid.
=> Upgrade to http4s-0.13-SNAPSHOT

swagger/src/main/scala/org/http4s/rho/swagger/TypeBuilder.scala, swagger/src/test/scala/org/http4s/rho/swagger/TypeBuilderSpec.scala
We are using `AnyVals` to model query parameters which are `String` or `Int` and give them a bit more type safety.
I propose that those `AnyVals` are not being considered as independent models but just as wrappers around the underlying value. Not doing this creates an invalid Swagger file for us and I didn't find any convenient work-around.
=> The DataType of an AnyVal should be the DataType of its underlying type.

.travis.yml, bin/travis
Currently they fail to build because PR's cannot access encryption keys (a good thing).
This PR moves the decryption process to non-pr's that actually need them.
=> Try and fix travis PR's

swagger/src/main/scala/org/http4s/rho/swagger/SwaggerSupport.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerSupportSpec.scala
This is useful for us in order to generate a Swagger YAML file which we can commit for review before committing to a given API.
The recursive lazy values in the `apply` method seem to work ok and allow the removal of the `var` :-).
=> Extracted a method from SwaggerSupport to create the Swagger spec

swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerModelsBuilderSpec.scala
@bryce-anderson I need something like that to:
- accept a `X-Flow-Id` header if the client passes on
- generate a `X-Flow-Id` header otherwise
And have `required=false` in the swagger file for that header parameter.
Does it make sense to you too?
=> [swagger] For a header parameter, set the `required` flag to false if there is a default value

project/build.scala, swagger/src/main/scala/org/http4s/rho/swagger/models.scala, swagger/src/test/scala/org/http4s/rho/swagger/Arbitraries.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerSpec.scala
This prevents empty 'examples' and 'headers' fields to be generated for responses.
The biggest contribution of this PR is actually arbitraries for a `Swagger` model. They are far from complete but they allow to test this change.
=> Translate empty maps in a Swagger model to null in the Java model 

swagger/src/main/scala/org/http4s/rho/swagger/models.scala
The `ObjectProperty` is part of the Java Swagger model and is actually useful for me in order to avoid having to create and reference another definition when I can just nest attributes.
=> Added an object property to nest attributes on a definition

swagger/src/main/scala/org/http4s/rho/swagger/models.scala
@bryce-anderson this is not essential but helps us describing the content of the JWT token we are using.
=> Added the possibility to add the description of an ApiKeyAuth security definition

swagger/src/main/scala/org/http4s/rho/swagger/SwaggerFileResponse.scala, swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala, swagger/src/main/scala/org/http4s/rho/swagger/TypeBuilder.scala, swagger/src/main/scala/org/http4s/rho/swagger/package.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerModelsBuilderSpec.scala
@bryce-anderson feel free to change the naming of the marker trait.
Also note that I changed slightly the primitive type check from using `=:=` to `<:<`. I think this is working ok but maybe you prefer to consider `file` as an entirely separate case and not treat it as "primitive" (it is a Swagger primitive type but not a Scala one).
=> Add the possibility to specify a swagger 'file' type for a given response

swagger/src/main/scala/org/http4s/rho/swagger/TypeBuilder.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerFormatsSpec.scala, swagger/src/test/scala/org/http4s/rho/swagger/TypeBuilderSpec.scala
This fixes #138
The `Property` type is actually recursive, in that `ArrayProperty` can contain inner properties. This wasn't being used correctly as could be seen if trying to use a Seq[Int] as the type: Int would be incorrectly represented as a `RefProperty`.
=> Allow more complex Property types in models

examples/src/main/scala/com/http4s/rho/swagger/demo/MyService.scala, swagger/src/main/scala/org/http4s/rho/swagger/TypeBuilder.scala, swagger/src/test/scala/org/http4s/rho/swagger/TypeBuilderSpec.scala
Fixes issue #140
Problem
The Option type was being passed to DataType.fromType
which doesn't know about custom serializers.
Solution
Unwrap the Option wrapper and `TypeBuilder.typeToProperty` and
recurse.
=> Correctly use custom serializers with Option wrapped types

examples/src/main/scala/com/http4s/rho/swagger/demo/MyService.scala, swagger/src/main/scala/org/http4s/rho/swagger/TypeBuilder.scala, swagger/src/test/scala/org/http4s/rho/swagger/TypeBuilderSpec.scala
Current master mistakenly generates schema definitions for swagger file responses. Example:
<pre>
"definitions":{"SwaggerFileResponseÂ«StringÂ»":{"required":["value"],"properties":{"value":{"type":"string"}},"description":"SwaggerFileResponseÂ«StringÂ»"}
</pre>
This PR fixes that by omitting SwaggerFileResponse objects when building the model.
=> Fix file response schema

swagger/src/main/scala/org/http4s/rho/swagger/SwaggerSupport.scala
Makes schema much more readable and makes the line numbers from Swagger Editor error messages much more helpful.
As the Swagger-schema is normally only used for dev/documentation purposes, I think the increase in size shouldn't be a problem.
=> Use pretty-printing for swagger schema.

swagger/src/main/scala/org/http4s/rho/swagger/SwaggerSupport.scala
Personally, I thought it was a little weird that the swagger routes were showing up in swagger.  So I've added an option to disable this while leaving the default behavior the same.
=> Added option to disable swagger routes in swagger

core/src/main/scala/org/http4s/rho/CompileService.scala, core/src/main/scala/org/http4s/rho/RhoService.scala, core/src/main/scala/org/http4s/rho/RouteExecutable.scala, core/src/main/scala/org/http4s/rho/ServiceBuilder.scala, core/src/main/scala/org/http4s/rho/bits/PathTree.scala, core/src/main/scala/org/http4s/rho/bits/ResultResponse.scala, core/src/test/scala/org/http4s/rho/ApiTest.scala, core/src/test/scala/org/http4s/rho/CompileServiceSpec.scala, core/src/test/scala/org/http4s/rho/RhoServiceSpec.scala
We have a lot of API surface right now that should probably not be exposed. This commit starts to trim away the things that aren't necessary for public consumption.
Targets include:
* RouteExecutable: `runWith` is unnecessary and very inefficient.
* CompileService: pull ServiceBuilder into its own file and clean it up.
* Minor other changes.
This is a binary incompatible change, but shouldn't be controversial.
=> Clean up a few sections of the API

swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerModelsBuilderSpec.scala
Without this PR we get errors on our Swagger spec with paths like
```
/bar
/bar/<id>
```
Note that the path parameters are now collected in the declaration order `L.121`. There are other places where we do the same kind of reversal during the Swagger construction.
Review @bryce-anderson 
cc @jcranky
=> Generate unique operation ids for paths having different parameters

core/src/main/scala/org/http4s/rho/package.scala, core/src/test/scala/org/http4s/rho/ParamDefaultValueSpec.scala
When the query param extractors or header extracts fail, the
error messages now include the name and the value.
=> Added QueryParam name and HeaderKey name to error messages.

swagger/src/main/scala/org/http4s/rho/swagger/SwaggerSupport.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerSupportSpec.scala
Factor out Swagger routes (/swagger.json) creation so it can be reused
when the Swagger Specification is an aggregate from multiple `RhoService`s
=> Generate Swagger docs from multiple `RhoService`s. Fixes #166

swagger/src/main/scala/org/http4s/rho/swagger/TypeBuilder.scala, swagger/src/main/scala/org/http4s/rho/swagger/models.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerModelsBuilderSpec.scala, swagger/src/test/scala/org/http4s/rho/swagger/TypeBuilderSpec.scala
According to [the `discriminator` spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#models-with-polymorphism-support). There's still two description fields - one in the `ComposedModel` and one in the `RefModel`. Not sure how to fix that.
Also, how should the discriminator field be passed in? Via an annotation?
=> Swagger descriptions for sum types

core/src/main/scala/org/http4s/rho/AuthedContext.scala, core/src/test/scala/org/http4s/rho/AuthedContextSpec.scala
This is needed because we need to let user specify any RhoMiddleware they want.
=> For #14 accept HttpService instead of RhoService

core/src/main/scala/org/http4s/rho/bits/ResultResponse.scala
This is necessary for more complex responses, like if you want to use
problem json.
=> Allow FailureResponses to be created with entities

swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerSupportSpec.scala
This allows people to define a route with a final section of `/ ""` to insist that there's a slash on the end.
=> Allow swagger routes with trailing slashes in Rho Swagger

core/src/main/scala/org/http4s/rho/bits/TypedASTs.scala, core/src/test/scala/org/http4s/rho/ApiTest.scala
Corrected a Copy-Paste Error on the TypedHeader.map implementation from PR #169
=> Fix TypedHeader map method return type.

swagger/src/main/scala/org/http4s/rho/swagger/SwaggerSupport.scala, swagger/src/main/scala/org/http4s/rho/swagger/models.scala, swagger/src/test/scala/org/http4s/rho/swagger/Arbitraries.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerSupportSpec.scala
The current implementation of the SwaggerSupport Middleware hid/didn't expose many of the available swagger configurations, like:
host, schemes, basePath, consumes, produces, security, securityDefinitions & vendorExtensions
Also The OAuth2Definition for security required a didn't allow for vendorExtensions and required tokenUrl.
So added OAuth2VendorExtensionsDefinition not to break compatibility.
=> swagger-middleware-extension

core/src/main/scala/org/http4s/rho/bits/Metadata.scala, swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala, swagger/src/main/scala/org/http4s/rho/swagger/package.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerModelsBuilderSpec.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerSupportSpec.scala
Added way to define security scopes to RhoRoute:
using ^^ syntax to prefix a Map[String, List[String]] of security scopes
eg:
`Map("auth0_jwk"->List("admin")) ^^ "Description" ** GET / "foo" |>> { () => Ok("bar") }`
=> security-scopes

build.sbt, core/src/main/scala/org/http4s/rho/bits/ResponseGenerator.scala, core/src/main/scala/org/http4s/rho/bits/ResultResponse.scala, core/src/test/scala/org/http4s/rho/ApiTest.scala, core/src/test/scala/org/http4s/rho/CodecRouterSpec.scala, core/src/test/scala/org/http4s/rho/ParamDefaultValueSpec.scala, core/src/test/scala/org/http4s/rho/RequestRunner.scala, core/src/test/scala/org/http4s/rho/ResultSpec.scala, core/src/test/scala/org/http4s/rho/RhoServiceSpec.scala, core/src/test/scala/org/http4s/rho/bits/HListToFuncSpec.scala, core/src/test/scala/org/http4s/rho/bits/PathTreeSpec.scala, core/src/test/scala/org/http4s/rho/bits/ResponseGeneratorSpec.scala, examples/src/main/scala/com/http4s/rho/swagger/demo/MyService.scala, project/build.scala
Upgrades the existing release-0.16.x branch to latest scalaz version of http4s (0.16.5).
Need to decide on a version number and create a new branch to merge into (if different branch is desired).
=> Upgrade to http4s 0.16.5, Fixes #204

examples/src/main/scala/com/http4s/rho/hal/plus/swagger/demo/RestService.scala, examples/src/main/scala/com/http4s/rho/swagger/demo/MyService.scala
Widening response types to `F[BaseResult[F]]` loses information
about the actual responses.
We can make this compile by making `F` covariant.
=> Fix examples with different response codes

swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerModelsBuilderSpec.scala
Right now if the body is a List[A] or some collection, the generated swagger lists the parameter as List«A».
This PR fixes that and now we correctly encode it as an ArrayProperty.
=> Handle Collection[A] in body parameter

swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerModelsBuilderSpec.scala
Corrects issue #257 where an `Option` of some container will register as an array of that container instead of a not required container.
=>  Fix issue #257

swagger/src/main/scala/org/http4s/rho/swagger/TypeBuilder.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerModelsBuilderSpec.scala, swagger/src/test/scala/org/http4s/rho/swagger/TypeBuilderSpec.scala
This pull request:
* Fixes #268. Unrelated models are no longer accidentally modified.
* Changes behaviour in case only some subtypes of a sum type are in use. Now the whole sum type (the type and all it's children) are added to the model.
* Adds support for multi-level sum types. See the "Build a model for two-level sealed trait hierarchy" test case.
* Adds some tests, including some not directly related to sub types handling.
* Fixes some issues discovered in the process, namely: infinite recursion for `FooEither` and `BTree` types (see the test cases)
* cleans up/unifies the way `alreadyKnown` and `known` are used (mainly in order to fix the infinite recursion issues)
=> Reworked handling of sum types. Solution for #268

swagger/src/main/scala/org/http4s/rho/swagger/TypeBuilder.scala, swagger/src/main/scala/org/http4s/rho/swagger/package.scala, swagger/src/test/scala/org/http4s/rho/swagger/TypeBuilderSpec.scala
Adds support for using value classes (classes extending AnyVal). In models they are replaced by the type they enclose.
=> Handle value classes transparently. Solution for #272

swagger/src/main/scala/org/http4s/rho/swagger/TypeBuilder.scala, swagger/src/test/scala/org/http4s/rho/swagger/TypeBuilderSpec.scala
Add missing sym.isClass check in isObjectEnum
Add tests for partially working shapeless coproducts and classes parametrised by type parameter of an outer type.
=> Partially fix #203

core/src/main/scala/org/http4s/rho/bits/HListToFunc.scala
Removing the `Lazy` on the `ResultMatcher` (which is only barely recursive on situations of `F[ResultMatcher]` seems to fix the issue in #216 with circe `Encoder` causing a compilation issue.
Reproduction requires this dependency: 
`"io.circe" %% "circe-core" % "0.10.0"`
Minimum reproduction.
```
import cats.effect.Effect
import io.circe.Encoder
import org.http4s._
import org.http4s.rho.RhoRoutes
trait Auto
class Test[F[+_]: Effect] extends RhoRoutes[F] {
implicit def autoEncoder[A <: Auto : Encoder]: EntityEncoder[F, A] = ???
GET / "get" |>> ({ () => // Didn't work.  Used Lazy[ResultMatcher]
Ok(())
})
GET / "get2" |>> ({ // Worked.  Does not use Lazy[ResultMatcher]
Ok(())
})
}
```
I'm still wondering how I can make a test, I haven't isolated what it is about the circe `Encoder` that …
=> Fix issue #216

swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala, swagger/src/main/scala/org/http4s/rho/swagger/models.scala, swagger/src/test/scala/org/http4s/rho/swagger/Arbitraries.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerModelsBuilderSpec.scala
`ListMap` keeps the insertion order in take, where `Map` does not guarantee it.
=> Issue 299 Maintain the order of inserted paths in swagger

core/src/main/scala/org/http4s/rho/QueryBuilder.scala, core/src/test/scala/ApiExamples.scala, examples/src/main/scala/com/http4s/rho/swagger/demo/MyRoutes.scala
There was a missing link in the chain
PathBuilder -> QueryBuilder -> CodecRouter
What was available
PathBuilder -> QueryBuilder -> Router -> CodecRouter
PathBuilder -> Router -> CodecRouter
PathBuilder -> CodecRouter
=> Fix issue 301, POST with body and query string, with no header extractor

core/src/main/scala/org/http4s/rho/bits/Metadata.scala, core/src/main/scala/org/http4s/rho/package.scala, core/src/test/scala/org/http4s/rho/ApiTest.scala, project/build.properties, swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerModelsBuilderSpec.scala
The `capture*` family of functions had a `default` parameter that allowed a default response to be sent when a header was not present, but did not have a way to set a default value for a header that was not present, or to optionally capture a header (that is, use an `Option`).  
This PR renames the old `default` parameter to make more sense, fixes the broken swagger values that was being set for it, and adds ways to default, or optionally capture headers.
=> Fix Header capture 'default' semantics

core/src/main/scala/org/http4s/rho/RhoDslHeaderExtractors.scala, core/src/main/scala/org/http4s/rho/RhoDslPathExtractors.scala, core/src/main/scala/org/http4s/rho/RhoDslQueryParamExtractors.scala, core/src/main/scala/org/http4s/rho/package.scala
moving path, query and header extractors to their own files so future refactoring will be easier.
Nothing has changed, just been moved around.
(Working on custom error messages)
=> RhoDSL extractor refactor

examples/src/main/scala/com/http4s/rho/swagger/demo/MyRoutes.scala, swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala, swagger/src/main/scala/org/http4s/rho/swagger/SwaggerSyntax.scala, swagger/src/main/scala/org/http4s/rho/swagger/package.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerModelsBuilderSpec.scala
Fixes #314.
I went with `@@` for the syntax to get things rolling, but I'm not tied to it. I plan to have a follow-up PR that adds alphanumeric aliases for it and the other existing methods as part of #315.
=> Add support for user-provided route tags.

core/src/main/scala/org/http4s/rho/AuthedContext.scala
Code given as an example inside of scaladoc for `AuthedContext` didn't compile.
Here is a small fix.
=> Fix scaladoc example for AuthedContext

examples/src/main/scala/com/http4s/rho/swagger/demo/MyRoutes.scala
Counter example contained a bug - invoking the route multiple times would always return 0.
Here is a small fix.
I also changed the method from `GET` to `POST`, as it is not an idempotent operation.
=> Fix counter example

swagger/src/main/scala/org/http4s/rho/swagger/TypeBuilder.scala, swagger/src/test/scala/org/http4s/rho/swagger/TypeBuilderSpec.scala
Treat `case object`s the same as `case class`es with 0 fields.
Fixes #339
=> #339 Allow mixing case classes and case objects in selaed traits. 

swagger/src/main/scala/org/http4s/rho/swagger/TypeBuilder.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerModelsBuilderSpec.scala, swagger/src/test/scala/org/http4s/rho/swagger/TypeBuilderSpec.scala
I've noticed that my swagger files fail validation when I have `case class Result[T](t: T msg: String)` and then use `Result[Unit]`. The problem is that rho emits a swagger schema with a property with `"type": "Unit"`. It isn't directly stated in swagger specification that `type` can't be an arbitrary string, but it turns out this requirement is inherited from JSON Schema.
This PR changes rho's behaviour when handling Unit/Void/Nothing/Null to:
- When building a model, emit a `RefProperty` referring to the definition of "Unit/Void/Nothing/Null" 
- Fall back to "string" where refs aren't allowed (query params, pathVars etc.)
=> Fix validation failures caused by Unit/Void/Nothing/Null

core/src/main/scala/org/http4s/rho/CompileRoutes.scala, core/src/main/scala/org/http4s/rho/RhoRoutes.scala, core/src/main/scala/org/http4s/rho/RoutesBuilder.scala
Relax the `Sync` constraint to `Defer` and `Monad` which should allow the use of `Eval` and not `SyncIO` for some purposes (such as testing)
@rossabaker Do you have some thoughts on this?
=> Relaxing Sync constrainton RhoRoutes

core/src/main/scala/org/http4s/rho/bits/ResultMatcher.scala, core/src/main/scala/org/http4s/rho/package.scala
This is a follow up to the profiling of compilation times of rho routes started in #417.
Let's start with an analysis of the current performance profile of the [Benchmark5_TypedPathAndComplexResult](https://github.com/RafalSumislawski/rho/blob/compilation-benchmarks/benchmark/src/main/scala/com/http4s/rho/swagger/demo/Benchmark5_TypedPathAndComplexResult.scala). 
The whole width of the flame chart is 12640ms. The lookup for ResultMatcher[F, F[Result[...]]] that I'm trying to optimize in this PR is 9450ms (75%).
- A - failed attempts to use the `writableMatcher` - problem solved by 
d5de0a6 
- B - `FnToProduct` and a `Reverse` this part will be doubled by #417
- C - building HList of the inputs (path vars in this case)
- D - lots of searches for `maybeWritableAny` (on for each `Nothing` in …
=> Speed up ResultMatcher implict lookups

swagger-ui/src/main/scala/com/http4s/rho/swagger/ui/SwaggerUi.scala, swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala, swagger/src/main/scala/org/http4s/rho/swagger/SwaggerSupport.scala, swagger/src/main/scala/org/http4s/rho/swagger/TypeBuilder.scala, swagger/src/main/scala/org/http4s/rho/swagger/package.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerFormatsSpec.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerModelsBuilderSpec.scala, swagger/src/test/scala/org/http4s/rho/swagger/TypeBuilderSpec.scala
The default behaviour remains unchanged. The way names are generated can be customised by providing a custom `ShowType` instance. This customisability is not limited to generic types, so if someone wishes to let's say, convert CamelCase class names into kebab-case type names in swagger that's also possible.  
Internally the `ShowType` is propagated as an implicit. On the API surface it's handled analogically to `SwaggerFormats` (non-implicit param with a default value).
Fixes #416
=> Make names of generic types customisable

swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala, swagger/src/main/scala/org/http4s/rho/swagger/SwaggerSupport.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerModelsBuilderSpec.scala
This is a fix for #448. 
There are already tests ("find a simple or-path" and "find a capture or-path") which exercise the scenario leading to this issue, but due to the way the assertions are formulated the problem is not detected. Redefinition of these tests is also part of this PR.
The issue actually has impact not only on tags, but generally on every difference between the alternatives defined with `||` . The root cause of the issue is that `SwaggerModelsBuilder.mkOperation` works on a `RhoRoute`, while a single `RhoRoute` may represent more than one operation in swagger model. Information belonging to these alternative operations gets mixed up. The solution is to split single `RhoRoute` into multiple routes, each representing one of the alternatives (I named them `LinearRoute`s) and …
=> Fix generation of swagger for alternative routes (routes with || )

swagger-ui/src/main/scala/com/http4s/rho/swagger/ui/SwaggerUi.scala, swagger-ui/src/main/scala/com/http4s/rho/swagger/ui/SwaggerUiRoutes.scala
I've noticed that `F` being covariant (`F[+_]`) in `SwaggerUi` and `SwaggerUiRoutes` is not only unnecessary (the covarience is not used in any way), but it causes issues when working with an `F` which is invariant, like for example `ReaderT[IO, A]`. Therefore in this PR I'm proposing to remove the requirment of covariance.
=> Relax variance constraint on F in SwaggerUi/SwaggerUiRoutes

build.sbt, core/src/test/scala/org/http4s/rho/ApiTest.scala, core/src/test/scala/org/http4s/rho/AuthedContextSuite.scala, core/src/test/scala/org/http4s/rho/CodecRouterSuite.scala, core/src/test/scala/org/http4s/rho/CompileRoutesSuite.scala, core/src/test/scala/org/http4s/rho/ParamDefaultValueSuite.scala, core/src/test/scala/org/http4s/rho/RequestRunner.scala, core/src/test/scala/org/http4s/rho/ResultSuite.scala, core/src/test/scala/org/http4s/rho/RhoRoutesSuite.scala, core/src/test/scala/org/http4s/rho/bits/HListToFuncSuite.scala, core/src/test/scala/org/http4s/rho/bits/PathTreeSuite.scala, core/src/test/scala/org/http4s/rho/bits/ResponseGeneratorSuite.scala, core/src/test/scala/org/http4s/rho/bits/ResultMatcherSuite.scala, project/Dependencies.scala, swagger/src/test/scala/org/http4s/rho/swagger/SwaggerSupportSuite.scala
Getting rid of `cats.effect.IOPlatform#unsafeRunSync` in tests.
=> Use `munit-cats-effect` in tests

README.md
Symbol literal is deprecated in 2.13 and removed in 3
=> Replace symbol literal with pv in Readme

Rho.md
auth doesn't have a parameter list, so don't use it in the call, so we don't incur any warnings.
=> Doc: remove parameter list from Auth.auth

core/src/main/scala/org/http4s/rho/RhoRoutes.scala
update for https://github.com/http4s/rho/issues/606
=> Remove prescriptive RhoRoutes logger
